[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[dependencies]
tdlib = { git = "https://github.com/melix99/tdlib-rs" }
tokio = { version = "1.22", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
] }
async-trait = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
url = "2.3"
serde = "1.0"
serde_json = "1.0"
image = { version = "0.24", default-features = false, features = [
    "png",
    "webp",
] }
base64 = "0.20.0-alpha"
time = { version = "0.3", features = ["serde", "serde-well-known", "macros"] }
dotenv = "0.15"
tempfile = "3.3"
log = { version = "0.4", features = ["std"] }
colored = "2.0"
counter = "0.5"
charname = "0.2"
