[package]
name = "craiyon-bot"
version = "1.0.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"
nursery = "warn"

[dependencies]
async-signal = "0.2"
async-trait = "0.1"
base64 = "0.22"
bytes = "1.6"
charname = "0.2"
colored = "2.1"
counter = "0.5"
dotenvy = "0.15"
futures-util = "0.3"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
log = { version = "0.4", features = ["std"] }
markov-chain = { git = "https://github.com/JelNiSlaw/markov-chain" }
md5 = "0.7"
oneshot = "0.1"
rand = "0.9.0-alpha"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream", "multipart"] }
rmp-serde = "1.3"
serde = "1.0"
serde_json = "1.0"
tdlib = { git = "https://github.com/JelNiSlaw/tdlib-rs-latest" }
tempfile = "3.10"
time = { version = "0.3", features = ["macros", "serde", "serde-well-known"] }
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "signal", "time"] }
url = "2.3"
